map_server_keepout:
  ros__parameters:
    use_sim_time: False
    yaml_filename: ""

costmap_filter_info_server:
  ros__parameters:
    use_sim_time: False
    type: 0
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/keepout_filter_mask"
